---
root: true
extends:
  - eslint:recommended
  - plugin:vue/vue3-recommended
rules:
  comma-dangle:
    - error
    - always
  operator-linebreak:
    - error
    - before
  no-mixed-operators:
    - error
  max-len:
    - error
    - 80
    - 2
