export default [
  {
    name: '808X Kit',
    samplePaths: [
      '/samples/808x/kick-808x-1.aac',
      '/samples/808x/clap-808x.aac',
      '/samples/808x/snare-808x-1.aac',
      '/samples/808x/closed-hh-808x.aac',
      '/samples/808x/open-hh-808x.aac',
      '/samples/808x/shaker-808x.aac',
      '/samples/808x/crash-808x.aac',
      '/samples/808x/hi-tom-808x.aac',
      '/samples/808x/mid-hi-tom-808x.aac',
      '/samples/808x/low-tom-808x.aac',
      '/samples/808x/mid-low-tom-808x.aac',
    ],
  },
  {
    name: 'Loungin Kit',
    samplePaths: [
      '/samples/loungin/kick-loungin.aac',
      '/samples/loungin/clap-1-loungin.aac',
      '/samples/loungin/clap-2-loungin.aac',
      '/samples/loungin/closed-hh-loungin.aac',
      '/samples/loungin/open-hh-loungin.aac',
      '/samples/loungin/shaker-loungin.aac',
      '/samples/loungin/snare-roll-loungin.aac',
      '/samples/loungin/conga-1-loungin.aac',
      '/samples/loungin/conga-2-loungin.aac',
      '/samples/loungin/conga-3-loungin.aac',
    ],
  },
  {
    name: 'She Traps Kit',
    samplePaths: [
      '/samples/she-traps/kick-2-she-traps.aac',
      '/samples/she-traps/snare-1-she-traps.aac',
      '/samples/she-traps/snare-2-she-traps.aac',
      '/samples/she-traps/closed-hh-1-she-traps.aac',
      '/samples/she-traps/open-hh-1-she-traps.aac',
      '/samples/she-traps/shaker-she-traps.aac',
      '/samples/she-traps/kick-1-she-traps.aac',
      '/samples/she-traps/hi-tom-1-she-traps.aac',
      '/samples/she-traps/mid-tom-2-she-traps.aac',
      '/samples/she-traps/perc-1-she-traps.aac',
      '/samples/she-traps/perc-2-she-traps.aac',
    ],
  },
];
